# Numpy Basics

In [1]:
%pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [42]:
import numpy as np

In [43]:
arr=np.array([21,2,1])

In [44]:
arr

array([21,  2,  1])

In [45]:
type(arr)

numpy.ndarray

In [46]:
A=np.array([1,2,3])

In [47]:
np.dot(arr,A)

28

In [48]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [49]:
%%time
arr+A

CPU times: total: 0 ns
Wall time: 0 ns


array([22,  4,  4])

In [50]:
arr*A

array([21,  4,  3])

In [51]:
(arr*A).sum()

28

# Multi-dimensional Numpy Array

In [52]:
climate_data=np.array([
    [13,67,43],
    [91, 88, 64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
])

In [53]:
climate_data

array([[ 13,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [54]:
climate_data.shape

(5, 3)

In [55]:
weights=np.array([.3,.2,.5])

In [56]:
weights

array([0.3, 0.2, 0.5])

In [57]:
weights.shape

(3,)

In [58]:
weights.dtype

dtype('float64')

In [59]:
climate_data.dtype

dtype('int32')

Matrix Multiplication

In [60]:
np.matmul(climate_data,weights)

array([38.8, 76.9, 81.9, 57.7, 74.9])

In [61]:
climate_data@weights

array([38.8, 76.9, 81.9, 57.7, 74.9])

# Working with CSV Files

In [62]:
import urllib.request

In [64]:
urllib.request.urlretrieve('https://www.kaggle.com/datatattle/dtmart-retail-sales','data.txt')

('data.txt', <http.client.HTTPMessage at 0x1ce03746980>)

In [65]:
%pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [66]:
import pandas as pd

In [82]:
data=pd.read_csv('./amazon_men.csv',delimiter=',',encoding='unicode_escape')

In [83]:
data

Product Description  Price(Dollar)  \
0      Vertx Cutback Mens Tactical Shorts 11 inches, ...            62   
1      Storelli Jumper Socks by Floky, Biomechanical ...            49   
2      Storelli Re-Charge Recovery Socks by Floky, Bi...            49   
3      Nike Men's Dri-Fit Training Cotton Cushioned C...            25   
4      Gildan Men's Crew T-Shirts, Multipack, Style G...            42   
...                                                  ...           ...   
23948       Amazon Essentials Men's Corduroy Chino Pants            37   
23949         Paul Smith Men's Standard Short Long Zebra           NaN   
23950   Tommy Bahama Long Sleeve Indigo Beach Camp Shirt           NaN   
23951  Kanu Surf Men's South Beach Swim Trunks (Regul...           NaN   
23952   Volcom Men's Iconic Stone Fleece 20" SweatShorts           NaN   

      Number of reviews Real price(Dollar)             Shipment Delivery Date  \
0                     2              14.00  Ships to Bangladesh   Thu, Jun 15   
1                 1,652              22.00  Ships to Bangladesh   Thu, Jun 15   
2               259,463              30.00  Ships to Bangladesh   Thu, Jun 15   
3                52,469              26.00  Ships to Bangladesh   Thu, Jun 15   
4                27,762              20.50  Ships to Bangladesh   Thu, Jun 15   
...                 ...                ...                  ...           ...   
23948                84               None  Ships to Bangladesh   Wed, Jun 21   
23949                84               None  Ships to Bangladesh   Wed, Jun 21   
23950                84               None  Ships to Bangladesh   Wed, Jun 21   
23951                84               None                 & Up   Wed, Jun 21   
23952                84               None                 & Up   Wed, Jun 21   

      How many sell  in past month  
0        10K+ bought in past month  
1        10K+ bought in past month  
2         6K+ bought in past month  
3        10K+ bought in past month  
4         7K+ bought in past month  
...                            ...  
23948    100+ bought in past month  
23949    100+ bought in past month  
23950    100+ bought in past month  
23951    100+ bought in past month  
23952    100+ bought in past month  

[23953 rows x 7 columns]

In [84]:
data.shape


(23953, 7)